# Generated by Django 4.1 on 2022-08-11 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
