services:
  web:
    build: .
    command: gunicorn project.wsgi -b 0.0.0.0:8000 
    environment:
      - DEBUG=0
      - EMAIL_HOST_USER=djangoemailsends@gmail.com
      - EMAIL_HOST_PASSWORD=qreppppnvrttqrym
      - ENVIRONMENT=production
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"