# Generated by Django 4.1 on 2022-08-23 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_studio_delete_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='studio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='games.studio'),
        ),
    ]
