# Generated by Django 4.1 on 2022-08-24 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_game_studio'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='game',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
