# Generated by Django 4.1 on 2022-08-29 16:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0012_comment_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 8, 29, 16, 42, 26, 651100)),
        ),
    ]
