# Generated by Django 4.1 on 2022-08-29 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0013_comment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
