# Generated by Django 4.1 on 2022-09-06 20:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0021_alter_comment_date_alter_grade_number_favoriteitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 6, 20, 2, 1, 767753)),
        ),
    ]
